myproject/my_app/urls.py
from django.urls import path
from .views import HomeView, ServicesView, BookingView, AboutView, ServiceDetailView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'my_app'
urlpatterns = [
    path('', HomeView.as_view() , name='home'),
    path('services/', ServicesView.as_view(), name='services'),
    path('services/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('booking/', BookingView.as_view(), name='booking'),
    path('about/', AboutView.as_view(), name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
]

myproject/my_app/models.py
from django.db import models
# Create your models here.
class Services(models.Model):
    name = models.CharField(max_length=20, default=None)
    description = models.TextField(default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=None)
    class Meta:
        db_table = 'Services'
    def __str__(self):
        return f"{self.name}"

class Reservation(models.Model):
    name = models.CharField(max_length=20, default=None)
    time = models.TimeField(default=None)
    date = models.DateField(default=None)
    class Meta:
        db_table = 'Reservation'
    
    def __str__(self):
        return f"{self.name} - {self.date} - {self.time}"
    

myproject/my_app/forms.py
from django import forms

from .models import Reservation

class BookingForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your name'}),
            'time': forms.TimeInput(attrs={'class': 'form-control', 'placeholder': 'Select time'}),
            'date': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Select date'}),
        }

myproject/my_app/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import Services
from .forms import BookingForm
from django.views.generic import TemplateView, ListView, FormView, DetailView
    
class HomeView(TemplateView):
    template_name = 'main.html'

class ServicesView(ListView):
    model = Services
    context_object_name = 'services_list'
    template_name = 'services.html'
    paginate_by = 10

    def get_queryset(self):
        return Services.objects.all().order_by('-name')

class ServiceDetailView(DetailView):
    model = Services
    template_name = 'service_detail.html'
    context_object_name = 'service'

class BookingView(FormView):
    form_class = BookingForm
    success_url = '/booking/'
    template_name = 'booking.html'

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Booking Confirmed!')
        return super().form_valid(form)

    
class AboutView(TemplateView):
    template_name = 'about.html'

myproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Hair Day</title>
    <link rel="stylesheet" type="text/css" href= "{% static 'css/hdstyles.css' %}" >
</head>
<body>
    {% include "partials/header.html" %}
    {% include "partials/nav.html" %}
    {% block content %}
    {% endblock  %}
    {% include "partials/footer.html" %}
    
</body>
</html>

myproject/templates/booking.html
{% extends "base.html" %}
{% load static %}
{% block title %}Booking{% endblock %}
{% block content %}
<section class="booking">
    <div class="booking-form">
        <h1>Book a Visit</h1>
        <form method="POST" action="/booking/" class ="form">
            {% csrf_token %}
            <div>
                <label for="name">Name:</label>
                <input type="text" id="name" name="name" required>
            </div>
            <div>
                <label for="time">Preferred Time:</label>
                <input type="time" id="time" name="time" required>
            </div>
            <div>
                <label for="date">Preferred Date:</label>
                <input type="date" id="date" name="date" required>
            </div>
            <button type="submit" class="btn">Confirm Booking</button>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}    
        </form>
    </div>
</section>
{% endblock %}

myproject/templates/main.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="promotion">        
            <img src="{% static 'images/Promotion.jpg' %}" alt="Promotion Image" class="promotion-image">
            <h2>Special Promotion</h2>
            <p>Get 20% off on all services<br>
                Valid until 31st December 2021</p>
</section>
<section class="catalogue">
        <h2>Our Style Catalogue</h2>
        <img src="{% static 'images/Catalogue.jpg' %}" alt="Catalogue">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio aspernatur, at fugit corrupti ducimus autem excepturi cum asperiores animi facilis optio, provident voluptate voluptatem a molestias in ipsa laboriosam. Laborum blanditiis fuga numquam ut illo perspiciatis rerum provident! Delectus, fuga! Vel, expedita labore perspiciatis veritatis accusantium explicabo unde voluptatum eos?</p>
</section>
<section class="appointment">
        <h2>Book an Appointment</h2>
        <img src="{% static 'images/appointment.jpg' %}" alt="Appointment">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio aspernatur, at fugit corrupti ducimus autem excepturi cum asperiores animi facilis optio, provident voluptate voluptatem a molestias in ipsa laboriosam. Laborum blanditiis fuga numquam ut illo perspiciatis rerum provident! Delectus, fuga! Vel, expedita labore perspiciatis veritatis accusantium explicabo unde voluptatum eos?</p>
</section>
<section class="timing">
        <h2>Opening Hours</h2>
        <img src="{% static 'images/Closed.jpeg' %}" alt="Sorry, we are closed">
        <p class="para">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Pariatur corrupti culpa incidunt neque veritatis omnis autem repellat nisi tenetur ex.</p>
        <p>Monday - Friday: 9:00 AM - 8:00 PM</p>
        <p>Saturday: 10:00 AM - 6:00 PM</p>
        <p>Sunday: Closed</p>
</section>
{% endblock %}

myproject/templates/partials/footer.html
{% load static %}

<footer class="footer">
        <img src="{% static 'images/Artboard 22.png' %}" alt="footer image">
        <hr>
        <p>Contact us: 123-456-7890<br>
        Hair Day<sup>&copy;</sup></p>
</footer>

myproject/templates/partials/header.html
{% load static %}

<header class="header">
    <img src="{% static 'images/Artboard 1.png' %}" alt="HAIR DAY">
</header>

myproject/templates/partials/nav.html
{% load static %}

<nav class="nav">
    <ul>
        <a href="{% url 'my_app:home' %}"><li>Home</li></a>
        <a href="{% url 'my_app:services' %}"><li>Services</li></a>
        <a href="{% url 'my_app:booking' %}"><li>Booking</li></a>
        <a href="{% url 'my_app:about' %}"><li>About</li></a>
    </ul>
</nav>

myproject/templates/service_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Our Services{% endblock %}
{% block content %}
<section class="services">
    <div class="service">
        <span>
            <a href="{% url 'my_app:home' %}">Home</a>/
            <a href="{% url 'my_app:services' %}">Services</a>/
            <a href="{% url 'my_app:service_detail' service.pk %}">{{service.name}}</a>
        </span>
        <img src="{% static 'images/' %}{{ service.name }}.jpg" alt="Services" class="services-image">
        <div class="service-details">
            <h1>{{service.name}}</h1><br>
            <p>{{service.description}}</p><br>
            <p>Price: ${{service.price}}</p><br>
            <a href="{% url 'my_app:booking' %}"><button class="btn">Book A Visit</button></a>
        </div>
    </div>
</section>
{% endblock %}

myproject/templates/services.html
{% extends "base.html" %}
{% block title %}Our Services{% endblock %}
{% load static %}
{% block content %}
<section class="services">
    <ul class="services-list">
        {% if services_list|length == 0 %}
            <p>No services available at the moment.</p>
        {% else %}
            <p>We have the following services available at the moment:</p>
        {% endif %}
        {% for item in services_list %}
            <li>
                <a href= "{% url 'my_app:service_detail' item.pk %}"><h2>{{ item.name }}</h2></a>
                <p>{{ item.description|truncatewords:10 }}</p>
                <p>Price: ${{ item.price }}</p>
            </li>
        {% endfor %}
    </ul>
</section>

{% endblock %}